<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ParcInformatique_ns="http://www.convertigo.com/convertigo/projects/ParcInformatique" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://www.convertigo.com/convertigo/projects/ParcInformatique">
    <xsd:element name="ParcInformatiquedb__create_composant" type="ParcInformatique_ns:ParcInformatiquedb__create_composantRequestData">
        <xsd:annotation>
            <xsd:documentation><![CDATA[Create one composant row.
]]></xsd:documentation>
        </xsd:annotation>
    </xsd:element>
    <xsd:element name="ParcInformatiquedb__create_composantResponse">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="response" type="ParcInformatique_ns:ParcInformatiquedb__create_composantResponseData"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="ParcInformatiquedb__create_composantResponseType">
        <xsd:sequence>
            <xsd:element name="document" type="ParcInformatique_ns:ParcInformatiquedb__create_composantResponseData"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ParcInformatiquedb__create_composantRequestData">
        <xsd:sequence>
            <xsd:element name="n_serie" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[NSerie for composant.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="date_achat" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[DateAchat for composant.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="garantie" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Garantie for composant.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="num_retour" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[NumRetour for composant.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="date_retour" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[DateRetour for composant.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="date_renvoi" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[DateRenvoi for composant.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="commentaire" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Commentaire for composant.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="machine_id" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[MachineId foreign key referencing machines.id.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="modele_id" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[ModeleId foreign key referencing modeles.id.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="fournisseur_id" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[FournisseurId foreign key referencing fournisseurs.id.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ParcInformatiquedb_create_composant_document_errorType">
        <xsd:sequence>
            <xsd:element minOccurs="0" name="code" type="xsd:byte"/>
            <xsd:element minOccurs="0" name="message" type="xsd:string"/>
            <xsd:element minOccurs="0" name="details" type="xsd:anyURI"/>
            <xsd:element minOccurs="0" name="context" type="xsd:anyURI"/>
            <xsd:element minOccurs="0" name="exception" type="xsd:anyURI"/>
            <xsd:element minOccurs="0" name="stacktrace" type="xsd:anyURI"/>
        </xsd:sequence>
        <xsd:attribute name="connector" type="xsd:anyURI"/>
        <xsd:attribute name="project" type="xsd:anyURI"/>
        <xsd:attribute name="transaction" type="xsd:anyURI"/>
        <xsd:attribute default="string" name="type" type="xsd:anyURI"/>
    </xsd:complexType>
    <xsd:complexType name="ParcInformatiquedb__create_composantResponseData">
        <xsd:sequence>
            <xsd:element minOccurs="0" name="error" type="ParcInformatique_ns:ParcInformatiquedb_create_composant_document_errorType"/>
            <xsd:element minOccurs="0" name="sql_output" type="xsd:string"/>
            <xsd:element minOccurs="0" name="error" type="ParcInformatique_ns:ConvertigoError"/>
        </xsd:sequence>
        <xsd:attribute name="connector" type="xsd:anyURI"/>
        <xsd:attribute name="context" type="xsd:string"/>
        <xsd:attribute name="contextId" type="xsd:string"/>
        <xsd:attribute name="fromStub" type="xsd:boolean"/>
        <xsd:attribute name="fromcache" type="xsd:boolean"/>
        <xsd:attribute name="generated" type="xsd:string"/>
        <xsd:attribute name="project" type="xsd:anyURI"/>
        <xsd:attribute name="sequence" type="xsd:anyURI"/>
        <xsd:attribute name="signature" type="xsd:long"/>
        <xsd:attribute name="transaction" type="xsd:anyURI"/>
        <xsd:attribute name="version" type="xsd:anyURI"/>
        <xsd:attribute name="screenclass" type="xsd:string"/>
        <xsd:attribute name="type" type="xsd:string"/>
        <xsd:attribute name="userReference" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="ConvertigoErrorContextVariable">
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="ConvertigoErrorContext">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="variable" type="ParcInformatique_ns:ConvertigoErrorContextVariable"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ConvertigoError">
        <xsd:sequence minOccurs="0">
            <xsd:element name="code" type="xsd:integer"/>
            <xsd:element name="message" type="xsd:string"/>
            <xsd:element name="details" type="xsd:string"/>
            <xsd:element name="context" type="ParcInformatique_ns:ConvertigoErrorContext"/>
            <xsd:element name="exception" type="xsd:string"/>
            <xsd:element name="stacktrace" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="project" type="xsd:string"/>
        <xsd:attribute name="connector" type="xsd:string"/>
        <xsd:attribute name="transaction" type="xsd:string"/>
        <xsd:attribute name="sequence" type="xsd:string"/>
        <xsd:attribute name="type">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="c8o"/>
                    <xsd:enumeration value="project"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
</xsd:schema>
