<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ParcInformatique_ns="http://www.convertigo.com/convertigo/projects/ParcInformatique" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://www.convertigo.com/convertigo/projects/ParcInformatique">
    <xsd:element name="ParcInformatiquedb__create_modele" type="ParcInformatique_ns:ParcInformatiquedb__create_modeleRequestData">
        <xsd:annotation>
            <xsd:documentation><![CDATA[Create one modele row.
]]></xsd:documentation>
        </xsd:annotation>
    </xsd:element>
    <xsd:element name="ParcInformatiquedb__create_modeleResponse">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="response" type="ParcInformatique_ns:ParcInformatiquedb__create_modeleResponseData"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="ParcInformatiquedb__create_modeleResponseType">
        <xsd:sequence>
            <xsd:element name="document" type="ParcInformatique_ns:ParcInformatiquedb__create_modeleResponseData"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ParcInformatiquedb__create_modeleRequestData">
        <xsd:sequence>
            <xsd:element name="type_modele" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[TypeModele for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="nom_modele" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[NomModele for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="marque" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Marque for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="caracteristique1" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Caracteristique1 for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="valeur1" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Valeur1 for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="caracteristique2" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Caracteristique2 for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="valeur2" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Valeur2 for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="caracteristique3" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Caracteristique3 for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="valeur3" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Valeur3 for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="caracteristique4" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Caracteristique4 for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="valeur4" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Valeur4 for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="commentaire" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[Commentaire for modele.]]></xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ParcInformatiquedb_create_modele_document_sql_outputType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:anyURI">
                <xsd:attribute default="string" name="type" type="xsd:anyURI"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="ParcInformatiquedb__create_modeleResponseData">
        <xsd:sequence>
            <xsd:element minOccurs="0" name="sql_output" type="ParcInformatique_ns:ParcInformatiquedb_create_modele_document_sql_outputType"/>
            <xsd:element minOccurs="0" name="error" type="ParcInformatique_ns:ConvertigoError"/>
        </xsd:sequence>
        <xsd:attribute name="connector" type="xsd:anyURI"/>
        <xsd:attribute name="context" type="xsd:string"/>
        <xsd:attribute name="contextId" type="xsd:string"/>
        <xsd:attribute name="fromStub" type="xsd:boolean"/>
        <xsd:attribute name="fromcache" type="xsd:boolean"/>
        <xsd:attribute name="generated" type="xsd:string"/>
        <xsd:attribute name="project" type="xsd:anyURI"/>
        <xsd:attribute name="sequence" type="xsd:anyURI"/>
        <xsd:attribute name="signature" type="xsd:long"/>
        <xsd:attribute name="transaction" type="xsd:anyURI"/>
        <xsd:attribute name="version" type="xsd:anyURI"/>
        <xsd:attribute name="screenclass" type="xsd:string"/>
        <xsd:attribute name="type" type="xsd:string"/>
        <xsd:attribute name="userReference" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="ConvertigoErrorContextVariable">
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="ConvertigoErrorContext">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="variable" type="ParcInformatique_ns:ConvertigoErrorContextVariable"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ConvertigoError">
        <xsd:sequence minOccurs="0">
            <xsd:element name="code" type="xsd:integer"/>
            <xsd:element name="message" type="xsd:string"/>
            <xsd:element name="details" type="xsd:string"/>
            <xsd:element name="context" type="ParcInformatique_ns:ConvertigoErrorContext"/>
            <xsd:element name="exception" type="xsd:string"/>
            <xsd:element name="stacktrace" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="project" type="xsd:string"/>
        <xsd:attribute name="connector" type="xsd:string"/>
        <xsd:attribute name="transaction" type="xsd:string"/>
        <xsd:attribute name="sequence" type="xsd:string"/>
        <xsd:attribute name="type">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="c8o"/>
                    <xsd:enumeration value="project"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
</xsd:schema>
